from django.db import models
from django.contrib.auth.models import User
from pharmacy_proj.common_timezones import COMMON_TIMEZONES
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class MedicationCategory(models.Model):
    """
Represents a category for medications.

Attributes:
    name (str): The name of the medication category.
    description (str): The description of the medication category.
"""
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

class Supplier(models.Model):
    """
Represents a supplier in the pharmacy system.

Attributes:
    company_name (str): The name of the supplier company.
    phone (str): The phone number of the supplier.
    address (str): The address of the supplier.

Methods:
    __str__(): Returns the company name of the supplier.
    get_list_of_orders(): Retrieves a list of orders associated with the supplier's medications.
"""
    company_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.company_name
    
    def get_list_of_orders(self):
        return [order for medication in self.medication_set.all() for order in medication.order_set.all()]

class PharmacyDepartment(models.Model):
    """
Represents a department within the pharmacy system.

Attributes:
    address (str): The address of the pharmacy department.

Methods:
    __str__(): Returns the address of the pharmacy department.
    get_total_revenue(): Calculates the total revenue generated by summing the total cost of all orders associated with the department.
"""
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.address
    
    def get_total_revenue(self):
        return sum((order.get_total_cost() for order in self.order_set.all()))

class Medication(models.Model):
    """
Represents a medication in the pharmacy system.

Attributes:
    code (str): The unique code of the medication.
    name (str): The name of the medication.
    instruction (str): The instructions for using the medication.
    description (str): The description of the medication.
    cost (Decimal): The cost of the medication.
    photo (ImageField): The photo of the medication.
    categories (ManyToManyField): The categories that the medication belongs to.
    supplier (ForeignKey): The supplier of the medication.
    date_created (DateTimeField): The date and time when the medication was created.

Methods:
    __str__(): Returns the name of the medication.
    get_total_revenue(): Calculates the total revenue generated by the medication through orders.
    get_total_number_of_ordered(): Calculates the total number of units ordered for the medication.
"""
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    instruction = models.TextField()
    description = models.TextField()
    cost = models.DecimalField(max_digits=8, decimal_places=2)
    photo = models.ImageField(upload_to='medication_photos')
    categories = models.ManyToManyField(MedicationCategory)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def get_total_revenue(self):
        return sum((order.get_total_cost() for order in self.order_set.all()))
    
    def get_total_number_of_ordered(self):
        return sum((order.quantity for order in self.order_set.all()))

class Employee(models.Model):
    """
Represents an employee in the pharmacy system.

Attributes:
    user (User): The user associated with the employee.
    date_of_birth (DateFiels): The date of birth of user.
    phone (str): The phone number of the employee.
    position (str): The position/title of the employee.
    salary (Decimal): The salary of the employee.
    photo (ImageField): The photo of the employee.
    timezone_info (str): The timezone information for the employee.
    suppliers (ManyToManyField): The suppliers associated with the employee.

Methods:
    __str__(): Returns the full name of the user associated with the employee.
"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()
    phone = models.CharField(max_length=20, default='')
    position = models.CharField(max_length=100)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='employee_photos')
    timezone_info = models.CharField(max_length=32, choices=tuple((el, el) for el in COMMON_TIMEZONES))
    suppliers = models.ManyToManyField(Supplier)

    def __str__(self):
        return self.user.get_full_name()
    
    def get_age(self):
        today = timezone.now().date()
        age = today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        return age
    
class Client(models.Model):
    """
Class representing a client in the system.

Attributes:
    user (User): A one-to-one relationship with the User model representing the client.
    age (PositiveIntegerField): The age of the client.
    phone (CharField): The phone number of the client.
    timezone_info (CharField): The timezone information of the client, chosen from a list of common timezones.
    
Methods:
    __str__: Returns the full name of the user associated with the client.
"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()
    phone = models.CharField(max_length=20)
    timezone_info = models.CharField(max_length=32, choices=tuple((el, el) for el in COMMON_TIMEZONES))

    def __str__(self):
        return self.user.get_full_name()
    
    def get_age(self):
        today = timezone.now().date()
        age = today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        return age
    
class CompanyInfo(models.Model):
    """
Represents information about the company in the system.

Attributes:
    text (str): The text containing information about the company.

Methods:
    __str__(): Returns the text containing information about the company.
"""
    text = models.TextField()
    
    def __str__(self):
        return self.text
    
class QuestionAnswer(models.Model):
    """
Represents a question and its corresponding answer in the system.

Attributes:
    question (TextField): The question asked.
    answer (TextField): The answer to the question.
    date_added (DateTimeField): The date and time when the question-answer pair was added.

Methods:
    __str__(): Returns the question text.
"""
    question = models.TextField()
    answer = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.question
    
class Promo(models.Model):
    """
Represents a promotional offer in the system.

Attributes:
    promo (str): The code for the promotional offer.
    description (str): The description of the promotional offer.
    is_active (bool): Indicates if the promotional offer is currently active.
    discount (Decimal): The discount percentage of the promotional offer.

Methods:
    __str__(): Returns the code of the promotional offer.
"""
    promo = models.CharField(max_length=20, unique=True)
    description = models.TextField()
    is_active = models.BooleanField()
    discount = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        validators=[
            MinValueValidator(0.00),
            MaxValueValidator(1.00),
        ])
    
    def __str__(self):
        return self.promo
    
class Review(models.Model):
    """
Represents a review in the system.

Attributes:
    full_name (str): The full name of the reviewer.
    text (str): The text content of the review.
    mark (int): The rating mark given to the review, ranging from 1 to 5.
    date_added (DateTime): The date and time when the review was added.
"""
    full_name = models.CharField(max_length=50)
    text = models.TextField()
    mark = models.IntegerField(
        default=1,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5),
        ])
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.text
    
class Vacancy(models.Model):
    """
Represents a job vacancy in the system.

Attributes:
    position (str): The position/title of the job vacancy.
    description (str): The description of the job vacancy.
    salary (Decimal): The salary offered for the job vacancy.
    requirements (str): The requirements or qualifications for the job vacancy.
    posted_date (Date): The date when the job vacancy was posted.

Methods:
    __str__(): Returns the position/title of the job vacancy.
"""
    position = models.CharField(max_length=100)
    description = models.TextField()
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    requirements = models.TextField()
    posted_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.position
    
class Order(models.Model):
    """
Represents an order in the pharmacy system.

Attributes:
    medication (ForeignKey): The medication associated with the order.
    client (ForeignKey): The client who placed the order.
    department (ForeignKey): The pharmacy department where the order was placed.
    quantity (PositiveIntegerField): The quantity of medication ordered.
    date_of_order (DateTimeField): The date and time when the order was placed.
    promo (ForeignKey): The promotional offer applied to the order, if any.

Methods:
    __str__(): Returns a string representation of the order showing the client and medication.
    get_total_cost(): Calculates the total cost of the order taking into account the medication cost, quantity, and any active promotional discount.
"""
    medication = models.ForeignKey(Medication, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    department = models.ForeignKey(PharmacyDepartment, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    date_of_order = models.DateTimeField(auto_now_add=True)
    promo = models.ForeignKey(Promo, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return str(self.client) + ', ' + str(self.medication)
    
    def get_total_cost(self):
        return round(self.medication.cost * self.quantity * (self.promo.discount if (self.promo is not None and self.promo.is_active) else 1), 2)
    
    
class News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    summary = models.TextField()
    image = models.ImageField(upload_to='news_photos')
    posted_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title