from matrix_calculation import *
from validation_functions import *

class TaskOutput:
    def __init__(self):
        '''
        Initialize a TaskOutput object.
        '''
        
        self.matrix_calc = MatrixCalculation(2, 2)
        
    def show_matrix(self):
        '''
        Display the matrix. This method prints the matrix generated by the MatrixCalculation object.
        '''
        
        print(self.matrix_calc.matrix)
        
    def input_for_sizes(self, size_name):
        '''
        Get user input for matrix size.

        Parameters:
        size_name (str): The name of the size parameter ('number of lines' or 'number of columns').
        '''

        print(f"Enter {size_name} (positive int value): ", end='')
        while True:
            try:
                value = consistent_validation(input(), int_validation, positive_validation)
                break
            except ValueError as ex:
                print(ex, ", try again: ", sep='', end='')
                
        if size_name == 'number of lines':
            self.matrix_calc.n = value
        elif size_name == 'number of columns':
            self.matrix_calc.m = value
            
    def input_for_random(self, rand_name):
        '''
        Get user input for random number range.

        Parameters:
        rand_name (str): The name of the range parameter ('min' or 'max').
        '''
        
        print(f"Enter {rand_name} (int value, min < max): ", end='')
        while True:
            try:
                value = consistent_validation(input(), int_validation)
                if rand_name == "max":
                    self.matrix_calc.rand_max = value
                elif rand_name == "min":
                    self.matrix_calc.rand_min = value
                break
            except ValueError as ex:
                print(ex, ", try again: ", sep='', end='')
                
    def print_results(self, func, text):
        '''
        Print the results of a matrix calculation.

        Parameters:
        func (callable): The matrix calculation function to be executed.
        text (str): The text to be displayed before the result.
        '''
        
        print(text, func(self.matrix_calc))